CREATE DATABASE UNGDUNGXEMPHIM

USE UNGDUNGXEMPHIM

GO

CREATE TABLE ACCOUNT
(
    USERNAME VARCHAR(30) NOT NULL,
    GMAIL VARCHAR(30) NOT NULL UNIQUE,
    PASS VARCHAR(30) NOT NULL,
    [ROLE] INT DEFAULT 0,
    CONSTRAINT PK_ACC PRIMARY KEY (USERNAME)
);
GO
INSERT ACCOUNT (USERNAME, GMAIL, PASS) VALUES ('thea6','anhvtph37751@fpt.edu.vn', 'theanh682004')

INSERT ACCOUNT VALUES ('thea7','anhvtph38851@fpt.edu.vn', 'theanh682004',1)

INSERT ACCOUNT VALUES ('thea8','anhvtph3991@fpt.edu.vn', 'theanh682004', 2)

UPDATE ACCOUNT SET GMAIL = ?, PASS = ? WHERE USERNAME = ?

SELECT * FROM ACCOUNT

DELETE ACCOUNT WHERE [USER] = 'theanh'